# Generated by Django 5.1 on 2024-09-27 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_dog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='data',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='dog',
            name='name',
            field=models.CharField(default='Default Dog Name', max_length=200),
        ),
    ]
