# Generated by Django 5.1 on 2024-09-27 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_dog_data_alter_dog_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeBlog',
            fields=[
                ('blog_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.blog')),
                ('theme', models.CharField(default='default_theme', max_length=100)),
            ],
            bases=('blog.blog',),
        ),
    ]
