# Generated by Django 5.1 on 2024-09-27 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_commonlyusedmodel_managedmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.CharField(default='Untitled Book', max_length=256),
        ),
        migrations.CreateModel(
            name='BookChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(help_text='Liên kết đến cuốn sách.', on_delete=django.db.models.deletion.CASCADE, related_name='book_chapters', to='blog.book')),
                ('chapter', models.ForeignKey(help_text='Liên kết đến chương.', on_delete=django.db.models.deletion.CASCADE, related_name='book_chapters', to='blog.chapter')),
            ],
            options={
                'verbose_name': 'Book Chapter',
                'verbose_name_plural': 'Book Chapters',
                'unique_together': {('book', 'chapter')},
            },
        ),
        migrations.AddField(
            model_name='book',
            name='chapters',
            field=models.ManyToManyField(help_text='Danh sách các chương thuộc về cuốn sách này.', related_name='books', through='blog.BookChapter', to='blog.chapter'),
        ),
    ]
