# Generated by Django 5.1 on 2024-09-26 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_place_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.CharField(help_text='Địa chỉ', max_length=80),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(help_text='Tên', max_length=50),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='place_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myapp.place'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='serves_hot_dogs',
            field=models.BooleanField(default=False, help_text='hotdog?'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='serves_pizza',
            field=models.BooleanField(default=False, help_text='pizza?'),
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myapp.place')),
                ('customers', models.ManyToManyField(help_text='nhà cung cấp', related_name='providers', to='myapp.place')),
            ],
            bases=('myapp.place',),
        ),
    ]
